services:
  nonebot:
    build: .
    image: xana278/nonebot

    container_name: nb
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./:/nonebot"
    environment:
      - TIME_ZONE=Asia/Shanghai
    command: sh -c "python bot.py"
    working_dir: /nonebot
    restart: always

  go-cqhttp:
    image: alpine
    container_name: go
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./go-cqhttp:/go-cqhttp"
    working_dir: /go-cqhttp
    command: sh -c "./go-cqhttp"
    restart: always
