services:
  nonebot:
    image: registry.cn-hangzhou.aliyuncs.com/xana278/dao-bot
    container_name: nb
    network_mode: host
    volumes:
      - "./data:/nonebot/data"
      - "./config:/nonebot/config"
    command: sh -c "python3 bot.py"
    working_dir: /nonebot
    restart: always
    environment:
      - ENVIRONMENT=prod
      - APP_MODULE=bot:app
      - MAX_WORKERS=1

  go-cqhttp:
    image: alpine
    container_name: go
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./go-cqhttp:/go-cqhttp"
    working_dir: /go-cqhttp
    command: sh -c "./go-cqhttp"
    restart: always
