[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.poetry]
authors = ["kexue <xana278@foxmail.com>"]
description = ""
name = "dao-Bot"
version = "0.1.0"

[tool.poetry.dependencies]
aiofiles = "^0.7.0"
bilibili-api = "^6.1.2"
boto3 = "^1.18.59"
brotlipy = "^0.7.0"
dnspython = "^2.1.0"
httpx = "^0.20"
nonebot-adapter-onebot = "^2.0.0-beta.1"
nonebot-plugin-apscheduler = "^0.1.2"
nonebot-plugin-htmlrender = "^0.0.4"
nonebot-plugin-remake = "^0.2.3"
nonebot-plugin-setu-now = "^0.0.4.3-beta.1"
nonebot2 = "^2.0.0-beta.1"
numpy = "^1.22.1"
pillow = "^8.3.1"
playwright = "^1.17.2"
pypinyin = "^0.42.0"
python = "^3.9"
pyzbar-x = "^0.2.1"
ujson = "^4.0.2"
wolframalpha = "^5.0.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.10b0", allow-prereleases = true}

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[nonebot]
[nonebot.plugins]
plugin_dirs = ["plugins"]
plugins = [
  "nonebot_plugin_remake",
  "nonebot_plugin_setu_now",
]
