[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true
[tool.poetry]
name = "dao-Bot"
version = "0.1.0"
description = ""
authors = ["kexue <xana278@foxmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
nonebot-plugin-status = "^0.2.1"
nonebot-hk-reporter = "^0.3.1"
nonebot-plugin-gamedraw = "^0.1.8"
nonebot-plugin-apscheduler = "^0.1.2"
nonebot-plugin-statistical = "^0.4.3"
nonebot-plugin-cocdicer = "^0.2.4"
nonebot-plugin-wordbank = "^1.0.2"
nonebot-plugin-manager = "^0.5.3"
ujson = "^4.0.2"
bilibili-api = "^6.1.2"
pillow = "^8.3.1"
dnspython = "^2.1.0"
aiofiles = "^0.7.0"
pypinyin = "^0.42.0"
matplotlib = "^3.4.2"
nonebot-plugin-test = "^0.3.0"
wolframalpha = "^5.0.0"
boto3 = "^1.18.59"
brotlipy = "^0.7.0"
nonebot2 = "2.0.0a16"
nonebot-plugin-picsearcher = "0.1.6rc1"
webdav4 = "^0.9.3"

[tool.poetry.dev-dependencies]
black = {version = "^21.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[nonebot]
[nonebot.plugins]
plugins = []
plugin_dirs = []
