# [[tool.poetry.source]]
# default = true
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"

[tool.poetry]
authors = ["kexue <xana278@foxmail.com>"]
description = ""
name = "dao-Bot"
version = "0.1.0"

[tool.poetry.dependencies]
bilibili-api = "^9.1.0"
cos-python-sdk-v5 = "^1.9.15"
nonebot-adapter-onebot = "^2.0.0-beta.1"
nonebot-bison = "^0.5.0"
nonebot-plugin-cocdicer = "^0.3.1"
nonebot-plugin-heweather = "^0.5.5"
nonebot-plugin-manager = "^0.5.0"
nonebot-plugin-petpet = "^0.2.11"
nonebot-plugin-picsearcher = "^0.1.7"
nonebot-plugin-remake = "^0.2.4"
nonebot-plugin-setu-now = "^0.1.0"
nonebot-plugin-trpglogger = "^0.4.0"
nonebot-plugin-withdraw = "^0.2.0"
nonebot-plugin-word-bank2 = "^0.1.4"
nonebot-plugin-youthstudy = "^1.0.4"
nonebot2 = "^2.0.0-beta.1"
python = "^3.9"
requests = "^2.27.1"
wolframalpha = "^5.0.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.10b0", allow-prereleases = true}
flake8 = "^4.0.1"
isort = "^5.10.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[nonebot]
[nonebot.plugins]
plugin_dirs = ["plugins"]
plugins = [
  "nonebot_plugin_remake",
  "nonebot_plugin_setu_now",
  "nonebot_plugin_heweather",
  "nonebot_plugin_trpglogger",
  "nonebot_plugin_cocdicer",
]
