
[project]
name = "dao-Bot"
version = "0.1.0"
description = ""
authors = [
    {name = "kexue", email = "xana278@foxmail.com"},
]
dependencies = [
    "dnspython>=2.2.1",
    "wolframalpha>=5.0.0",
    "nonebot-adapter-onebot>=2.2.3",
    "nonebot-plugin-heweather>=0.6.9",
    "nonebot-plugin-manager>=0.5.16",
    "nonebot-plugin-withdraw>=0.2.3",
    "nonebot-plugin-word-bank2>=0.1.8",
    "nonebot-plugin-setu-now>=0.4.4",
    "nonebot-bison>=0.7.3",
    "nonebot-plugin-dailysign>=0.0.2",
    "fastapi>=0.98.0",
]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = {file = "LICENSE"}


[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "black>=21.10b0",
    "flake8>=4.0.1",
    "isort>=5.10.1",
]

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
src_paths = ["plugins", "utils"]
extra_standard_library = ["typing_extensions"]
