host: 0.0.0.0
port: 9901
# debug:
superusers: !secret superusers
nickname:
  - 屑岛风
command_start:
  - "/"
  - "."
  - "。"
  - "!"
  - "！"
command_sep:
  - "."

log_level: INFO

# pushover
pushover_token: !secret pushover_token
pushover_user: !secret pushover_user

# heweather
qweather_apikey: !secret qweather_apikey
qweather_apitype: 1

# mcserver
mcserver_apikey: !secret mcserver_apikey
mcserver: !secret mcserver

# wolframalpha
wolframalpha_appid: !secret wolframalpha_appid

# proxy
clash_url: !secret clash_url
docker_url: http://192.168.0.49:8989/
proxy_url: http://192.168.0.49:9098/

# setu
setu_cd: 300

bison_use_pic: true
bison_use_queue: true
bison_to_me: false
BISON_USE_PIC_MERGE: 1
BISON_FILTER_LOG: true

repeat_count: 3

auth: !secret auth
