host: 127.0.0.1
port: 9901
# debug:
superusers: !secret superusers
nickname:
  - 屑岛风
command_start:
  - "/"
  - "."
  - "。"
  - "!"
  - "！"
command_sep:
  - "."
apikey: ""
log_level: INFO

# heweather
qweather_apikey: !secret qweather_apikey
qweather_apitype: 1

# mcserver
mcserver_apikey: !secret mcserver_apikey
mcserver: !secret mcserver

# wolframalpha
wolframalpha_appid: !secret wolframalpha_appid

# proxy
clash_url: !secret clash_url
docker_url: http://192.168.0.49:8989/
proxy_url: http://192.168.0.49:9098/

# setu
setu_cd: 30
# setu_save: webdav
# setu_dav_url: !secret setu_dav_url
# setu_dav_username: !secret setu_dav_username
# setu_dav_password: !secret setu_dav_password
setu_withdraw: 120

bison_use_pic: true
bison_use_queue: true
bison_to_me: false
