host: 0.0.0.0
port: 9901
driver: "~httpx+~websockets"

onebot_ws_urls: ["ws://127.0.0.1:6700"]

superusers: !secret superusers

command_start:
  - "/"

log_level: INFO
# log_level: DEBUG
# heweather
# qweather_apikey: !secret qweather_apikey
# qweather_apitype: 1

# db_url: !secret db_url
