plugins:
  - nonebot_plugin_apscheduler
  - nonebot_plugin_datastore
  - nonebot_plugin_htmlrender
  - nonebot_plugin_heweather
  - nonebot_plugin_word_bank2
  - nonebot_plugin_petpet
  - nonebot_plugin_manager
  - nonebot_plugin_withdraw
  - nonebot_bison
  - nonebot-plugin-cocdicer

plugin_dirs:
  - plugins
