plugins:
  - nonebot_plugin_heweather
  - nonebot_plugin_word_bank2
  - nonebot_plugin_manager
  - nonebot_plugin_withdraw
  - nonebot_bison
  - nonebot_plugin_setu_now
  - nonebot_plugin_eitherchoice

plugin_dirs:
  - plugins
