plugins:
  # - nonebot_plugin_manager
  # - nonebot_plugin_setu_now
  # - nonebot_plugin_mcsm
  # - nonebot_plugin_bracket
  # - nonebot_plugin_heweather
  # - nonebot_plugin_treehelp
  # - nonebot_plugin_marshoai
  # - ELF_RSS2
  - nonebot_bison
plugin_dirs:
  - plugins
