plugins:
  - nonebot_plugin_htmlrender
  - nonebot_plugin_heweather
  - nonebot_plugin_remake
  - nonebot_plugin_setu_now
  - nonebot_plugin_trpglogger
  - nonebot_plugin_cocdicer
  - nonebot_plugin_word_bank2
  - nonebot_plugin_petpet
  - nonebot_plugin_manager
  - nonebot_plugin_withdraw
  - nonebot_bison
  - nonebot_plugin_hikarisearch
  - nonebot_plugin_youthstudy
  - nonebot_plugin_qrcode
  - nonebot_plugin_minesweeper
  - nonebot_plugin_chess

plugin_dirs:
  - plugins
