name: Auto update CI

on:
  schedule:
    - cron: "0 20 * * 2,4,6"
  workflow_dispatch:

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python3.10
        uses: actions/setup-python@v3.1.2
        with:
          python-version: "3.10.x"

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Update
        run: poetry update --lock

      - name: Git Commit
        run: |
          git config --local user.email "bot@kexue.io"
          git config --local user.name "Bot"
          git add .
          git commit -m "auto update"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.APIKEY_GITHUB }}
