name: Docker Image CI

on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows:
      - Auto update CI
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag xana278/dao-bot
      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish
        run: docker push xana278/dao-bot
