name: Docker Image CI

on:
  push:
    tags:
      - "v*"
  workflow_run:
    workflows:
      - Auto update CI
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag xana278/dao-bot
      - name: Docker Login dockerhub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to dockerhub
        run: docker push xana278/dao-bot

      - name: Docker Login Aliyun
        uses: docker/login-action@v1.14.1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_USERNAME }}
          password: ${{ secrets.ALI_PASSWORD }}

      - name: Publish to Aliyun
        run: |
          docker tag xana278/dao-bot registry.cn-hangzhou.aliyuncs.com/xana278/dao-bot
          docker push registry.cn-hangzhou.aliyuncs.com/xana278/dao-bot
