name: PushOver Notification

on:
  workflow_run:
    workflows:
      - Docker Image CI
    types:
      - completed


jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: pushover action
        # You may pin to the exact commit or the version.
        # uses: umahmood/pushover-actions@5da31193f672e7418804bdb51836bdf20f393c8f
        uses: umahmood/pushover-actions@v1.1.0
        env:
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
        with:
          status: ${{ job.status }}
          message: "日常更新已完成"
          title: "Bot 自动更新"
